service: api


provider:
  name: aws
  runtime: nodejs12.x


iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"

functions:
  app-api:
    warmup: true
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true


plugins:
  - serverless-plugin-warmup